
# exception (예외)
# Error - copile time error : 문법오류
#       - runtime error : 실행시 발생하는 오류

# 어떤 runtime error들은 비정상 종료되지 않고 프로그램을 지속적으로
# 수행시킬 수 있는 방법이 있어요!

# try~
# except
# else
# finally

# def my_func(my_list):
#
#     # total_sum = 0  #list안의 숫자들을 누적해요!
#
#     try:
#         total_sum = my_list[0] + my_list[1] + my_list[2]
#         print("try가 수행되었어요!!")
#     except Exception:            #Exception은 발생할 수 있는 모든 오류를 지칭!
#         print("오류가 존재합니다.")    # 예외처리를 해야 해요!
#     else:
#         print("오류가 없어요!!")
#     finally:
#         print("무조건 수행되요!!")
#
# my_func([1,2])











